name: learn_toefl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_labeled_navigation_bar: ^2.0.2
  curved_navigation_bar: ^1.0.1
  sqflite: ^2.3.3
  path: ^1.9.0
  youtube_player_flutter: ^9.0.1
  google_fonts: ^6.2.0
  http: ^1.2.1
  audioplayers: ^6.0.0
  translator: ^1.0.0
  fluttertoast: ^8.2.5
  shared_preferences: ^2.2.3
  get: ^4.6.6
  speech_to_text: ^6.6.0
  cupertino_icons: ^1.0.0
  flutter_native_splash: ^2.4.0
  jwt_decoder: ^2.0.1


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/audio/
