name: learn_toefl
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  curved_labeled_navigation_bar: ^2.0.2
  curved_navigation_bar: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  


flutter:
  uses-material-design: true
  assets:
    - assets/images/
